### ISSUE TITLE
`workspace.rootPath` is deprecated

### ISSUE THREAD

**Issue by ericcornelissen** [Akecel/makefiles-runner#2]
I was looking at the source code of this and noticed [the usage of `workspace.rootPath`](https://github.com/Akecel/makefiles-runner/blob/c2ba70d06ae303076e924bf53890502545bcfeeb/src/provider.ts#L14), which has been deprecated. Thought I'd share this so it can be updated before it is removed in a future version of VS Code.

**Comment by Akecel** [comment]
Thank you for this information!

I had no idea, has this function been replaced by something else?

**Comment by ericcornelissen** [comment]
Yes sorry, [the type documentation](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9c8d9fec0a9fcf1d84ca1da6827325a42ad452cd/types/vscode/index.d.ts#L10082-L10088) says:


```ts
/**
 * ...
 * 
 * @deprecated — Use workspaceFolders instead
 */
```
